wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700476011.586335
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      3:
      - 7
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: test_loss_step
      5: 1
      6:
      - 1
    - 1: test_cosine_similarity_step
      5: 1
      6:
      - 1
